import json as js

json = {
	"table": "evidencias_adicionales",
	"rows":
	[
		{
			"checks_json": "{\"ocr_validation\": {\"data\": {\"name\": \"GINA VANESSA\", \"lastName\": \"CACERES NEJIA\", \"ID\": \"0801 1994 O9741\"}, \"percent\": {\"name\": \"100\", \"lastName\": \"90\", \"ID\": \"93\"}}, \"face_validation\": {\"liveness_test\": {\"movement\": true, \"antiSpoofing\": true}, \"confidence_test\": {\"confidence\": 0.5069506484245487, \"value\": false}, \"img1_data\": {\"faceLandmarks\": {\"x\": 173, \"y\": 189, \"w\": 116, \"h\": 116, \"left_eye\": [250, 233], \"right_eye\": [210, 236]}}, \"img2_data\": {\"faceLandmarks\": {\"x\": 151, \"y\": 232, \"w\": 80, \"h\": 80, \"left_eye\": null, \"right_eye\": null}}}, \"mrz_validation\": {\"code\": {\"raw\": \"Requiere verificar \\u2013 DATOS INCOMPLETOS\", \"preprocessed\": \"I<HNDO049277423<<<eccccececcceP404243F3104242HND<<<cxccccecgMEJTA<CACERES<<GINA<VANESSA<<<\"}, \"data\": {\"name\": \"GINA VANESSA\", \"lastName\": \"CACERES\"}, \"percentage\": {\"name\": \"100\", \"lastName\": \"70\"}}, \"barcode_validation\": {\"barcode\": \"OK\"}, \"sides_validation\": {\"front\": {\"correspond\": true, \"code\": \"HND\", \"country\": \"HONDURAS\", \"type\": \"no detectado\"}, \"back\": {\"correspond\": true, \"code\": \"HND\", \"country\": \"HONDURAS\", \"type\": \"DNI\"}}, \"checks\": {\"confidence\": false, \"movement\": true, \"antiSpoofing\": true, \"mrz_name\": true, \"mrz_lastname\": false, \"front_country\": true, \"front_type\": true, \"front\": true, \"back_country\": true, \"back_type\": true, \"back\": true, \"sides_country_confidence\": true, \"sides_type_confidence\": true, \"mrz\": false, \"barcode\": true, \"ocr_name\": true, \"ocr_lastname\": true, \"ocr_id\": true}, \"results_validation\": {\"validation_percentage\": 83.33333333333334}}",
			"estado_verificacion": "validación fallida"
		},
		{
			"checks_json": "{\"ocr_validation\": {\"data\": {\"name\": \"CARLOS ROBERTO\", \"lastName\": \"ZELAYA CORTES\", \"ID\": \"no encontrado\"}, \"percent\": {\"name\": \"100\", \"lastName\": \"100\", \"ID\": \"0\"}}, \"face_validation\": {\"liveness_test\": {\"movement\": true, \"antiSpoofing\": true}, \"confidence_test\": {\"confidence\": 0.32946734531238697, \"value\": true}, \"img1_data\": {\"faceLandmarks\": {\"x\": 189, \"y\": 148, \"w\": 224, \"h\": 224, \"left_eye\": [346, 236], \"right_eye\": [258, 236]}}, \"img2_data\": {\"faceLandmarks\": {\"x\": 160, \"y\": 215, \"w\": 76, \"h\": 76, \"left_eye\": null, \"right_eye\": null}}}, \"mrz_validation\": {\"code\": {\"raw\": \"<c<ccccccecccece750621 33 106213HND<<<<ccccccerZELAYA <CORTES<<CARLOS<ROBERTO<\", \"preprocessed\": \"<<ccccccececcce750621331062 13HND<<<<ccececeeZELAYA<CORTES<<CARLOS<ROBERTO<\"}, \"data\": {\"name\": \"CARLOS ROBERTO\", \"lastName\": \"ccececeeZELAYA CORTES\"}, \"percentage\": {\"name\": \"100\", \"lastName\": \"76\"}}, \"barcode_validation\": {\"barcode\": \"!OK\"}, \"sides_validation\": {\"front\": {\"correspond\": true, \"code\": \"HND\", \"country\": \"HONDURAS\", \"type\": \"no detectado\"}, \"back\": {\"correspond\": true, \"code\": \"HND\", \"country\": \"HONDURAS\", \"type\": \"DNI\"}}, \"checks\": {\"confidence\": true, \"movement\": true, \"antiSpoofing\": true, \"mrz_name\": true, \"mrz_lastname\": true, \"front_country\": true, \"front_type\": true, \"front\": true, \"back_country\": true, \"back_type\": true, \"back\": true, \"sides_country_confidence\": true, \"sides_type_confidence\": true, \"mrz\": true, \"barcode\": false, \"ocr_name\": true, \"ocr_lastname\": true, \"ocr_id\": false}, \"results_validation\": {\"validation_percentage\": 88.8888888888889}}",
			"estado_verificacion": "validación fallida"
		},
		{
			"checks_json": "{\"ocr_validation\": {\"data\": {\"name\": \"AOS ORO\", \"lastName\": \"TELAYA CONTES\", \"ID\": \"3975 O70 O70\"}, \"percent\": {\"name\": \"55\", \"lastName\": \"83\", \"ID\": \"53\"}}, \"face_validation\": {\"liveness_test\": {\"movement\": true, \"antiSpoofing\": true}, \"confidence_test\": {\"confidence\": 0.3885984676922838, \"value\": true}, \"img1_data\": {\"faceLandmarks\": {\"x\": 144, \"y\": 166, \"w\": 169, \"h\": 169, \"left_eye\": null, \"right_eye\": null}}, \"img2_data\": {\"faceLandmarks\": {\"x\": 199, \"y\": 217, \"w\": 64, \"h\": 64, \"left_eye\": null, \"right_eye\": null}}}, \"mrz_validation\": {\"code\": {\"raw\": \"<<<cccccccccece75062 13M3 10621 3HND<<<<<<c<cceeZELAYA<CORTES<<CARLOS<ROBERTOS\", \"preprocessed\": \"Requiere verificar \\u2013 DATOS INCOMPLETOS\"}, \"data\": {\"name\": \"CARLOS ROBERTOS\", \"lastName\": \"cceeZELAYA CORTES\"}, \"percentage\": {\"name\": \"96\", \"lastName\": \"86\"}}, \"barcode_validation\": {\"barcode\": \"!OK\"}, \"sides_validation\": {\"front\": {\"correspond\": true, \"code\": \"HND\", \"country\": \"HONDURAS\", \"type\": \"no detectado\"}, \"back\": {\"correspond\": true, \"code\": \"HND\", \"country\": \"HONDURAS\", \"type\": \"DNI\"}}, \"checks\": {\"confidence\": true, \"movement\": true, \"antiSpoofing\": true, \"mrz_name\": true, \"mrz_lastname\": true, \"front_country\": true, \"front_type\": true, \"front\": true, \"back_country\": true, \"back_type\": true, \"back\": true, \"sides_country_confidence\": true, \"sides_type_confidence\": true, \"mrz\": true, \"barcode\": false, \"ocr_name\": true, \"ocr_lastname\": true, \"ocr_id\": true}, \"results_validation\": {\"validation_percentage\": 94.44444444444446}}",
			"estado_verificacion": "validación fallida"
		},
		{
			"checks_json": "{\"ocr_validation\": {\"data\": {\"name\": \"OSWALDA\", \"lastName\": \"DIAZ AGUILERA\", \"ID\": \"0610 1972 00339\"}, \"percent\": {\"name\": \"100\", \"lastName\": \"100\", \"ID\": \"100\"}}, \"face_validation\": {\"liveness_test\": {\"movement\": true, \"antiSpoofing\": true}, \"confidence_test\": {\"confidence\": 0.5484508706468949, \"value\": false}, \"img1_data\": {\"faceLandmarks\": {\"x\": 221, \"y\": 113, \"w\": 223, \"h\": 223, \"left_eye\": null, \"right_eye\": null}}, \"img2_data\": {\"faceLandmarks\": {\"x\": 144, \"y\": 321, \"w\": 214, \"h\": 214, \"left_eye\": [298, 402], \"right_eye\": [210, 405]}}}, \"mrz_validation\": {\"code\": {\"raw\": \"I<HNDO0037253440<<<<<<cceececececec<7208056F3108055HND<<<<<ccecececcgDIAZ<AGUILERA<<OSWALDA<<<<ccecc\", \"preprocessed\": \"I<HNDO037253440<<<<<<ccceeecececc<7208056F3108055HND<<<<<ceceececcgDIAZ<AGUILERA<X<OSWALDA<<<<<c<c\"}, \"data\": {\"name\": \"OSWALDA\", \"lastName\": \"ccecececcgDIAZ AGUILERA\"}, \"percentage\": {\"name\": \"100\", \"lastName\": \"72\"}}, \"barcode_validation\": {\"barcode\": \"OK\"}, \"sides_validation\": {\"front\": {\"correspond\": true, \"code\": \"HND\", \"country\": \"HONDURAS\", \"type\": \"DNI\"}, \"back\": {\"correspond\": true, \"code\": \"HND\", \"country\": \"HONDURAS\", \"type\": \"DNI\"}}, \"checks\": {\"confidence\": false, \"movement\": true, \"antiSpoofing\": true, \"mrz_name\": true, \"mrz_lastname\": false, \"front_country\": true, \"front_type\": true, \"front\": true, \"back_country\": true, \"back_type\": true, \"back\": true, \"sides_country_confidence\": true, \"sides_type_confidence\": true, \"mrz\": true, \"barcode\": true, \"ocr_name\": true, \"ocr_lastname\": true, \"ocr_id\": true}, \"results_validation\": {\"validation_percentage\": 88.8888888888889}}",
			"estado_verificacion": "validación fallida"
		},
		{
			"checks_json": "{\"ocr_validation\": {\"data\": {\"name\": \"OSWALDA\", \"lastName\": \"DIAZ AGUILERA\", \"ID\": \"0610 1972 00339\"}, \"percent\": {\"name\": \"100\", \"lastName\": \"100\", \"ID\": \"100\"}}, \"face_validation\": {\"liveness_test\": {\"movement\": true, \"antiSpoofing\": true}, \"confidence_test\": {\"confidence\": 0.5016403385239789, \"value\": false}, \"img1_data\": {\"faceLandmarks\": {\"x\": 191, \"y\": 122, \"w\": 218, \"h\": 218, \"left_eye\": [341, 210], \"right_eye\": [259, 206]}}, \"img2_data\": {\"faceLandmarks\": {\"x\": 144, \"y\": 321, \"w\": 214, \"h\": 214, \"left_eye\": [298, 402], \"right_eye\": [210, 405]}}}, \"mrz_validation\": {\"code\": {\"raw\": \"I<HNDO0037253440<<<<<<cceececececec<7208056F3108055HND<<<<<ccecececcgDIAZ<AGUILERA<<OSWALDA<<<<ccecc\", \"preprocessed\": \"I<HNDO037253440<<<<<<ccceeecececc<7208056F3108055HND<<<<<ceceececcgDIAZ<AGUILERA<X<OSWALDA<<<<<c<c\"}, \"data\": {\"name\": \"OSWALDA\", \"lastName\": \"ccecececcgDIAZ AGUILERA\"}, \"percentage\": {\"name\": \"100\", \"lastName\": \"72\"}}, \"barcode_validation\": {\"barcode\": \"OK\"}, \"sides_validation\": {\"front\": {\"correspond\": true, \"code\": \"HND\", \"country\": \"HONDURAS\", \"type\": \"DNI\"}, \"back\": {\"correspond\": true, \"code\": \"HND\", \"country\": \"HONDURAS\", \"type\": \"DNI\"}}, \"checks\": {\"confidence\": false, \"movement\": true, \"antiSpoofing\": true, \"mrz_name\": true, \"mrz_lastname\": false, \"front_country\": true, \"front_type\": true, \"front\": true, \"back_country\": true, \"back_type\": true, \"back\": true, \"sides_country_confidence\": true, \"sides_type_confidence\": true, \"mrz\": true, \"barcode\": true, \"ocr_name\": true, \"ocr_lastname\": true, \"ocr_id\": true}, \"results_validation\": {\"validation_percentage\": 88.8888888888889}}",
			"estado_verificacion": "validación fallida"
		},
		{
			"checks_json": "{\"ocr_validation\": {\"data\": {\"name\": \"OSWALDA\", \"lastName\": \"DIAZ AGUILERA\", \"ID\": \"0610 1972 00339\"}, \"percent\": {\"name\": \"100\", \"lastName\": \"100\", \"ID\": \"100\"}}, \"face_validation\": {\"liveness_test\": {\"movement\": true, \"antiSpoofing\": true}, \"confidence_test\": {\"confidence\": 0.5286430235293571, \"value\": false}, \"img1_data\": {\"faceLandmarks\": {\"x\": 193, \"y\": 125, \"w\": 247, \"h\": 247, \"left_eye\": null, \"right_eye\": null}}, \"img2_data\": {\"faceLandmarks\": {\"x\": 144, \"y\": 321, \"w\": 214, \"h\": 214, \"left_eye\": [298, 402], \"right_eye\": [210, 405]}}}, \"mrz_validation\": {\"code\": {\"raw\": \"I<HNDO0037253440<<<<<<cceececececec<7208056F3108055HND<<<<<ccecececcgDIAZ<AGUILERA<<OSWALDA<<<<ccecc\", \"preprocessed\": \"I<HNDO037253440<<<<<<ccceeecececc<7208056F3108055HND<<<<<ceceececcgDIAZ<AGUILERA<X<OSWALDA<<<<<c<c\"}, \"data\": {\"name\": \"OSWALDA\", \"lastName\": \"ccecececcgDIAZ AGUILERA\"}, \"percentage\": {\"name\": \"100\", \"lastName\": \"72\"}}, \"barcode_validation\": {\"barcode\": \"OK\"}, \"sides_validation\": {\"front\": {\"correspond\": true, \"code\": \"HND\", \"country\": \"HONDURAS\", \"type\": \"DNI\"}, \"back\": {\"correspond\": true, \"code\": \"HND\", \"country\": \"HONDURAS\", \"type\": \"DNI\"}}, \"checks\": {\"confidence\": false, \"movement\": true, \"antiSpoofing\": true, \"mrz_name\": true, \"mrz_lastname\": false, \"front_country\": true, \"front_type\": true, \"front\": true, \"back_country\": true, \"back_type\": true, \"back\": true, \"sides_country_confidence\": true, \"sides_type_confidence\": true, \"mrz\": true, \"barcode\": true, \"ocr_name\": true, \"ocr_lastname\": true, \"ocr_id\": true}, \"results_validation\": {\"validation_percentage\": 88.8888888888889}}",
			"estado_verificacion": "validación fallida"
		},
		{
			"checks_json": "{\"ocr_validation\": {\"data\": {\"name\": \"GINA VANESSA\", \"lastName\": \"MEJIA CACERES\", \"ID\": \"0801 1994 09741\"}, \"percent\": {\"name\": \"100\", \"lastName\": \"100\", \"ID\": \"100\"}}, \"face_validation\": {\"liveness_test\": {\"movement\": true, \"antiSpoofing\": true}, \"confidence_test\": {\"confidence\": 0.5530915744622247, \"value\": false}, \"img1_data\": {\"faceLandmarks\": {\"x\": 139, \"y\": 67, \"w\": 200, \"h\": 200, \"left_eye\": [274, 150], \"right_eye\": [204, 149]}}, \"img2_data\": {\"faceLandmarks\": {\"x\": 59, \"y\": 179, \"w\": 129, \"h\": 129, \"left_eye\": null, \"right_eye\": null}}}, \"mrz_validation\": {\"code\": {\"raw\": \"I<HND0049277423<<<<<<<<<<<<<<<9404243 F3104242HND<<<<<<<<<<<8MEJ LASCACERES<<G INASVANESSA<<<IS\", \"preprocessed\": \"<HND0049277423<<<<<<<<<<<<<<<9404243 F3104242HND<<<<<<<<<<<3MEJIA<CACERES<<GINA<VANESSA<<< |\"}, \"data\": {\"name\": \"GINA VANESSA\", \"lastName\": \"3MEJIA CACERES\"}, \"percentage\": {\"name\": \"100\", \"lastName\": \"96\"}}, \"barcode_validation\": {\"barcode\": \"OK\"}, \"sides_validation\": {\"front\": {\"correspond\": true, \"code\": \"HND\", \"country\": \"HONDURAS\", \"type\": \"DNI\"}, \"back\": {\"correspond\": true, \"code\": \"HND\", \"country\": \"HONDURAS\", \"type\": \"DNI\"}}, \"checks\": {\"confidence\": false, \"movement\": true, \"antiSpoofing\": true, \"mrz_name\": true, \"mrz_lastname\": true, \"front_country\": true, \"front_type\": true, \"front\": true, \"back_country\": true, \"back_type\": true, \"back\": true, \"sides_country_confidence\": true, \"sides_type_confidence\": true, \"mrz\": true, \"barcode\": true, \"ocr_name\": true, \"ocr_lastname\": true, \"ocr_id\": true}, \"results_validation\": {\"validation_percentage\": 94.44444444444446}}",
			"estado_verificacion": "validación fallida"
		},
		{
			"checks_json": "{\"ocr_validation\": {\"data\": {\"name\": \"GINA VANESSA\", \"lastName\": \"MEJIA CACERES\", \"ID\": \"0801 1994 09741\"}, \"percent\": {\"name\": \"100\", \"lastName\": \"100\", \"ID\": \"100\"}}, \"face_validation\": {\"liveness_test\": {\"movement\": true, \"antiSpoofing\": true}, \"confidence_test\": {\"confidence\": 0.5365325180494727, \"value\": false}, \"img1_data\": {\"faceLandmarks\": {\"x\": 141, \"y\": 73, \"w\": 199, \"h\": 199, \"left_eye\": [275, 155], \"right_eye\": [204, 151]}}, \"img2_data\": {\"faceLandmarks\": {\"x\": 71, \"y\": 217, \"w\": 130, \"h\": 130, \"left_eye\": [160, 266], \"right_eye\": [112, 267]}}}, \"mrz_validation\": {\"code\": {\"raw\": \"<HNDO049277423<<<<<<Kccccccc<9404243F3104242HND<<<<<<<<<<<BME J IACCACERES<<GINA<VANESSA<\", \"preprocessed\": \"<HNDO049277423<<<<<<<<<<<<<<<9404243F3104242HND<<<<<<<<<<<8ME J TA<CACERES<<GINA<VANESSA<<<\"}, \"data\": {\"name\": \"GINA VANESSA\", \"lastName\": \"BME J IACCACERES\"}, \"percentage\": {\"name\": \"100\", \"lastName\": \"82\"}}, \"barcode_validation\": {\"barcode\": \"OK\"}, \"sides_validation\": {\"front\": {\"correspond\": true, \"code\": \"HND\", \"country\": \"HONDURAS\", \"type\": \"DNI\"}, \"back\": {\"correspond\": true, \"code\": \"HND\", \"country\": \"HONDURAS\", \"type\": \"DNI\"}}, \"checks\": {\"confidence\": false, \"movement\": true, \"antiSpoofing\": true, \"mrz_name\": true, \"mrz_lastname\": true, \"front_country\": true, \"front_type\": true, \"front\": true, \"back_country\": true, \"back_type\": true, \"back\": true, \"sides_country_confidence\": true, \"sides_type_confidence\": true, \"mrz\": true, \"barcode\": true, \"ocr_name\": true, \"ocr_lastname\": true, \"ocr_id\": true}, \"results_validation\": {\"validation_percentage\": 94.44444444444446}}",
			"estado_verificacion": "validación fallida"
		}
	]
}

rows = json["rows"]

for row in rows:

  checksImproten = ['confidence','antiSpoofing','movement', 'front', 'back', 'barcode', 'mrz']

  state = row['estado_verificacion']
  checksJson = row['checks_json']
  checksJson = js.loads(checksJson)
  checks = checksJson['checks']

  print('---', state, '---')
  for key in checks:
    if(key in checksImproten):
      print(key, checks[key])

